version: '3'

services:

  sandbox-frontend:
    container_name: sandbox-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/node_modules'
    ports:
      - 3000:3000
    networks:
      - sandbox-network

networks:
  sandbox-network:
    driver: bridge